# Configuración de la base de datos
database:
  host: "db-dtx-03.sparkedhost.us"
  port: 3306
  database: "s181642_ranked"
  username: "u181642_EmzxRextoT"
  password: "X4^pijD5zUWpY5UCrYM=W2e!"

discord:
  token: "Nzg0MDk4OTgyMDg2NDQzMDE4.GDlwFz.OmB4ZMp6gwf8ZkJN_bqYqbe_Wzq9QRRzsAU1xU"
  queue_role_name: "Queue"
# Configuración del servidor
server:
  name: "Keke Network"
  ip: "keke.sparked.network"

# Comandos para acceder a los servidores
commands:
  ranked: "/server keke1"
  mixed: "/server mixed"

# Configuración del sistema de compras
store:
  enabled: true
  check-interval: 30
  max-purchases-per-cycle: 10

# Mensajes informativos (SIN EMOJIS)
messages:
  server_info: |
    **Información del Servidor**

    IP del Servidor: `keke.sparked.network`

    Servidores disponibles:
    - Ranked: `/server keke1`
    - Mixed: `/server mixed`

  ip_info: |
    IP del Servidor: `keke.sparked.network`

    Para jugar Ranked: `/server keke1`
    Para jugar Mixed: `/server mixed`